# Generated by Django 5.0.6 on 2024-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('director', models.CharField(max_length=450)),
                ('cast', models.CharField(max_length=1050)),
                ('description', models.TextField(max_length=5500)),
                ('release_date', models.DateField()),
                ('averagerating', models.FloatField()),
            ],
        ),
    ]
