# Generated by Django 5.0.6 on 2024-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='averagerating',
            field=models.FloatField(default=0),
        ),
    ]
